import type { Metadata } from 'next';
import localFont from 'next/font/local';

import { cn } from '@/lib/utils';

import './globals.css';

const lineSeed = localFont({
  src: [
    {
      path: './fonts/LINESeedJP_OTF_EB.woff',
      weight: '800',
      style: 'extrabold',
    },
    {
      path: './fonts/LINESeedJP_OTF_Bd.woff',
      weight: '700',
      style: 'bold',
    },
    {
      path: './fonts/LINESeedJP_OTF_Rg.woff',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/LINESeedJP_OTF_Th.woff',
      weight: '100',
      style: 'thin',
    },
  ],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn([lineSeed.className, 'antialiased'])}>
        {children}
      </body>
    </html>
  );
}
