import type { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';

import MobileLayout from '@/components/layout/mobile-layout';
import { cn } from '@/lib/utils';
import { ClientSideProvider } from '@/providers/client';

import { fontSans } from '../fonts/config';
import '../globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body
        className={cn([fontSans.className, 'min-h-svh antialiased bg-gray-50'])}
      >
        <NextIntlClientProvider messages={messages}>
          <ClientSideProvider>
            <MobileLayout>{children}</MobileLayout>
          </ClientSideProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
